FROM python:3.12-slim-bookworm@sha256:31c0807da611e2e377a2e9b566ad4eb038ac5a5838cbbbe6f2262259b5dc77a0
COPY --from=docker.io/astral/uv:0.9@sha256:538e0b39736e7feae937a65983e49d2ab75e1559d35041f9878b7b7e51de91e4 /uv /uvx /bin/

WORKDIR /app

# Install outside the app folder to not conflict with code mounts
ENV UV_PROJECT_ENVIRONMENT=/usr/local/

RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --locked --no-install-project --no-dev

COPY . .

CMD ["fastapi", "run", "--host", "0.0.0.0", "/app/main.py"]
